# blogs/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import (
    BlogCardListView,
    BlogDetailView,
    CommentViewSet,
    get_vote_counts,
    submit_vote,
    undo_vote
)

# Create a router to automatically generate URLs for the Comment viewset
router = DefaultRouter()
router.register(r'comments', CommentViewSet, basename='comment')

# Define the URL patterns for the blogs app
urlpatterns = [
    # Main blog URLs
    path('blogs/', BlogCardListView.as_view(), name='blog-card-list'),
    path('blogs/<int:pk>/', BlogDetailView.as_view(), name='blog-detail'),

    # Vote-related URLs
    path('blogs/<int:blog_id>/votes/', get_vote_counts, name='get-vote-counts'),
    path('votes/submit/', submit_vote, name='submit-vote'),
    path('votes/undo/', undo_vote, name='undo-vote'),

    # URLs for comments, automatically generated by the router
    path('', include(router.urls)),
]