# Generated by Django 5.2.4 on 2025-07-20 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.URLField()),
                ('description', models.TextField()),
                ('author', models.CharField(max_length=100)),
                ('upload_date', models.DateField(auto_now_add=True)),
                ('rating', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='BlogDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_article', models.TextField()),
                ('author_image', models.URLField(blank=True, null=True)),
                ('about_author', models.TextField(blank=True, null=True)),
                ('blog_card', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detail', to='blogs.blogcard')),
            ],
        ),
    ]
