# Generated by Django 5.2.4 on 2025-07-20 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(help_text='A short description for the blog card.')),
                ('main_content', models.TextField(help_text='The full article content.')),
                ('blog_image', models.ImageField(upload_to='blog_images/')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('author_name', models.CharField(default='Admin', max_length=255)),
                ('author_image', models.ImageField(upload_to='author_images/')),
                ('about_author', models.TextField()),
                ('likes', models.PositiveIntegerField(default=0)),
                ('dislikes', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='blogdetail',
            name='blog_card',
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('comment_text', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blogs.blog')),
            ],
        ),
        migrations.DeleteModel(
            name='BlogCard',
        ),
        migrations.DeleteModel(
            name='BlogDetail',
        ),
    ]
