# Generated by Django 5.2.4 on 2025-07-20 15:09

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_blog_remove_blogdetail_blog_card_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='main_content',
            field=ckeditor.fields.RichTextField(help_text='The full article content.'),
        ),
    ]
