# Generated by Django 5.2.4 on 2025-07-21 10:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0006_comment_vote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='upload_date',
        ),
        migrations.AddField(
            model_name='blog',
            name='publish_date',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='The date and time the blog post is published. Can be edited for scheduling.'),
        ),
    ]
