# Generated by Django 5.2.4 on 2025-07-21 10:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0007_remove_blog_upload_date_blog_publish_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='publish_date',
            field=models.DateField(default=datetime.date.today, help_text='The date the blog post is published.'),
        ),
    ]
