# Generated by Django 5.2.4 on 2025-07-21 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0008_alter_blog_publish_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='user_session_id',
            field=models.CharField(default='', max_length=255),
        ),
    ]
