# Generated by Django 5.2.4 on 2025-07-23 06:13

import ckeditor.fields
import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0010_alter_vote_unique_together_remove_vote_blog_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='blog',
            name='author_name',
            field=models.CharField(default='Admin', max_length=255),
        ),
        migrations.AlterField(
            model_name='blog',
            name='description',
            field=models.TextField(help_text='A short description for the blog card.'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='main_content',
            field=ckeditor.fields.RichTextField(help_text='The full article content.'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='publish_date',
            field=models.DateField(default=datetime.date.today, help_text='The date the blog post is published.'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_session_id', models.CharField(default='', max_length=255)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blogs.blog')),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_session_id', models.CharField(max_length=255)),
                ('vote_type', models.SmallIntegerField(choices=[(1, 'Like'), (-1, 'Dislike')])),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='blogs.blog')),
            ],
            options={
                'unique_together': {('user_session_id', 'blog')},
            },
        ),
    ]
