# Generated by Django 5.2.4 on 2025-07-21 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blogs', '0005_alter_vote_unique_together_remove_vote_blog_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_session_id', models.CharField(max_length=255)),
                ('author_name', models.CharField(blank=True, max_length=100)),
                ('text', models.TextField(blank=True)),
                ('vote_type', models.SmallIntegerField(blank=True, choices=[(1, 'Like'), (-1, 'Dislike')], null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='blogs.blog')),
            ],
            options={
                'unique_together': {('user_session_id', 'blog')},
            },
        ),
    ]
